export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as TrustBadges } from "./TrustBadges";
export { default as Services } from "./Services";
export { default as PetSection } from "./PetSection";
export { default as Pricing } from "./Pricing";
export { default as FAQ } from "./FAQ";
export { default as Footer } from "./Footer";
export { default as FloatingWhatsApp } from "./FloatingWhatsApp";
